### ISSUE TITLE
Use Fast Robot Interface from TRI

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/kuka_iiwa_interface#87]
TRI uses the Fast Robot Interface (FRI) to control the Kuka Arms.
There are possibly numerous benefits to switching over.

**Comment by PeterMitrano** [comment]
We've looked into the potential benefits, and determined that we would lose significant functionality if we switched to FRI. Ideally we would have a stack which allowed one to easily use FRI or the Java+LCM stack, but that's for the future since none of the benefits of FRI (velocity control, it's probably faster) are critical at the moment.
